### ISSUE TITLE
[BUG] Update message appears every time players get near each other on a server.

### ISSUE THREAD

**Issue by Vaelzan** [andrew0030/Pandoras-Creatures#4] opened 2019-10-31 20:36 UTC
**Describe the bug**
The update available message displays every time a player approaches another on a SMP server from a distance. This is particularly noticeable when flying around with an elytra.

**To Reproduce**
1. Be on multiplayer server with more than one player online.
2. Approach other player (might be a 128 block distance, haven't checked exactly).
3. Update message displays.
4. Move back away out of range.
5. Repeat steps 2-4 to get infinite update chat messages.

**Expected behavior**
Give the update message at most once per session. Further, the config probably shouldn't even default to showing the message even once, as most players are likely to be playing on a modpack where they don't control the update frequency.

**Screenshots**
These messages were all within the space of ten seconds - I moved away from a player, then towards, then away, then towards, etc. This would be far worse if more than one other player was online. There were another six of these messages while I was writing this bug report without me moving.
https://imgur.com/PbVh4UT

**Note**
The Forge event that you are subscribed to likely fires for every player, every time they are loaded by the client. A simple fix may be ensuring that the player is the local player.

**Comment by andrew0030** [comment] 2019-11-01 12:33
Yeah my bad, it would seem like the event gets called more then once, the intended behavior for this message is for it to just show up once. As for the whole it shouldn't be true by default thing, I disagree you see, usually the people who don't play modpacks never look into the configs, and they just take it the way it is. Modpack creators on the other hand go through all the configs in order to balance the game and to fix issues. And all it takes is for the creator to turn it off and none of the clients will get the message ever unless they choose so by changing it back to true. Any ways I will make sure to fix this, until then I would recommend simply updating the mod version :P or disabling the message.

**Comment by andrew0030** [comment] 2019-11-01 13:18
Found the problem and fixed it, by making the message only appear once per session.
(Fixed in Mod versions after 1.14.4-0.11.0)

**Closed by andrew0030** 2019-11-01 13:18 UTC
Labels: bug
